### ISSUE TITLE
Not working with 5.8 - email gets sent but no Unsubscribe url in footer

### ISSUE THREAD

**Issue by heyaj19** [ylsideas/subscribable-notifications#19]
Hi Peter as discussed via email. 

I download the package using composer and did these few steps. 

Added App\Providers\SubscriberServiceProvider to my config/app.php also published it and changed the dummyuser to my User model as App\User

In my user Model i did the following 

     `        
             use YlsIdeas\SubscribableNotifications\MailSubscriber;
             use YlsIdeas\SubscribableNotifications\Contracts\CanUnsubscribe;
          class User extends Authenticatable implements CanUnsubscribe
            {
                   use HasApiTokens;
                  use  Notifiable, Rewardable, MailSubscriber;

      `

In my notification file I did this 

      `            use YlsIdeas\SubscribableNotifications\Contracts\AppliesToMailingList;

                  use YlsIdeas\SubscribableNotifications\Contracts\AppliesToMailingList;
                 class SendReceipts extends Notification implements AppliesToMailingList
             {
                     use Queueable;
                   protected $receiptRequest;
    /**
     * Create a new notification instance.
     *
     * @return void
     */
                public function __construct(array $receiptRequest)
                {
                       $this->receiptRequest = $receiptRequest;
              }
                public function usesMailingList(): string
              {
                  return 'receipts-list';
                 }`

The email goes through, but no unsubscribe url in footer.

**Comment by oleksiyPetlyuk** [comment]
@heyaj19 I have the same issue. Is your mail used in Notification class instance of `Illuminate\Notifications\Messages\MailMessage` or `Illuminate\Contracts\Mail\Mailable` ?
Seems that this package does not work properly with `Illuminate\Contracts\Mail\Mailable`.

`// Inject unsubscribe links for rendering in the view
        if ($notifiable instanceof CanUnsubscribe && $message instanceof MailMessage) {
            if ($notification instanceof AppliesToMailingList) {
                $message->viewData['unsubscribeLink'] = $notifiable->unsubscribeLink(
                    $notification->usesMailingList()
                );
            }
            $message->viewData['unsubscribeLinkForAll'] = $notifiable->unsubscribeLink();
        }`

**Comment by heyaj19** [comment]
@oleksiyPetlyuk  its MailMessage

`            

  namespace App\Notifications;

      use App\Http\Resources\GetBookingInfoForNotficationsResource;
      use Illuminate\Bus\Queueable;
      use Illuminate\Notifications\Notification;
      use Illuminate\Contracts\Queue\ShouldQueue;
         use Illuminate\Notifications\Messages\MailMessage;
        use Illuminate\Support\Facades\Log;
         use Carbon\Carbon;

       class SendReceipts extends Notification implements ShouldQueue
         {
                use Queueable;
               protected $receiptRequest;`

**Comment by peterfox** [comment]
@heyaj19 my initial tests show that the package should work fine with queuing but I'll admit I could do with doing a more comprehensive test of the package. It's possible that serialisation causes an issue with the generated MailMessage.

**Comment by heyaj19** [comment]
@peterfox  I took queue out as well and my emails were still getting sent just not the unsubscribe link. If it works for you we can set a video call and see what I need to do? 

I am going to spend more time on the package today to see if there is something I can find.

**Comment by heyaj19** [comment]
@peterfox  @oleksiyPetlyuk 

Figured it out -- I was faking an email user by sending it to an email defined on the env. So it was no t "sending" it to the user. I made some changes and it worked ...

**Comment by heyaj19** [comment]
Just a few questions -- What do you suggest is the best way to track unsubscribes in the DB?

**Comment by peterfox** [comment]
@heyaj19 I'm not quite sure what you mean by "How do I capture different models(guards) in the email link?"
