### ISSUE TITLE
Laravel 7 release

### ISSUE THREAD

**Issue by leeovery** [ylsideas/subscribable-notifications#22]
Hey,

Looks like the composer has been updated but a release hasnt been made.

Would it be possible to do a tag & release please?

Thanks!!!!
Lee

**Comment by leeovery** [comment]
@peterfox Just to add if you need anything PR'd please let me know. Happy to help :)

**Comment by peterfox** [comment]
@leeovery sorry about that, release 1.2.0 has been made.

**Comment by leeovery** [comment]
No need to apologise - thank you!
