### ISSUE TITLE
Hardcoded User model

### ISSUE THREAD

**Issue by Putr** [ylsideas/subscribable-notifications#24]
Issue is here:
https://github.com/ylsideas/subscribable-notifications/blob/fd84117056bc65b3efd3deb4fcedbc51a23709c4/src/Subscriber.php#L27

You are using a hardcoded user model class `App\User` even tho that's not a give. Lots of us use `App\Models\User` and if I'm not mistaken this is becoming the new standard.

You should probably use `auth.php` config, specifically `providers.users.model` where everyone configures their user model.

**Comment by peterfox** [comment]
Actually you can use the facade to change this:

```php
Subscriber::userModel('\App\Models\User');
```

Normally you'd just put this in the boot method of a service provider. I should document this better now though since the changes in Laravel 8.
