### ISSUE TITLE
Laravel 10 release

### ISSUE THREAD

**Issue by dbhynds** [ylsideas/subscribable-notifications#50]
### Discussed in https://github.com/ylsideas/subscribable-notifications/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **dbhynds** January 16, 2024</sup>
Hello.

I notice the composer.json on `main` has been updated to support Laravel 10, but a release hasn't been made. Would it be possible to have a release tagged, please?</div>

**Comment by dbhynds** [comment]
@peterfox Could we get some help with this?

**Comment by peterfox** [comment]
Done with the 1.5.0 release
